name: Release S3Khoj

on:
 push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
  
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.5
        
    - name: run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
          GITHUB_TOKEN: ${{ secrets.S3Khoj_GITHUB_TOKEN }}
